name: PHP CLI

on:
  workflow_dispatch:
    inputs:
      php74:
        description: "PHP 7.4 (latest)"
        default: '0'
        required: false
      php73:
        description: "PHP 7.3"
        default: '0'
        required: false
      php72:
        description: "PHP 7.2"
        default: '0'
        required: false
      php71:
        description: "PHP 7.1"
        default: '0'
        required: false
      php70:
        description: "PHP 7.0"
        default: '0'
        required: false

jobs:
  php74:
    if: ${{ github.event.inputs.php74 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cli
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: PHP_VERSION=7.4
          tags: |
            gabriel0702usesi/php-multi-arch:7.4
            ghcr.io/oreales/php-cli:7.4
            ghcr.io/oreales/php-cli:latest
  php73:
    if: ${{ github.event.inputs.php73 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cli
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: PHP_VERSION=7.3
          tags: |
            gabriel0702usesi/php-multi-arch:7.3
            ghcr.io/oreales/php-cli:7.3
  php72:
    if: ${{ github.event.inputs.php72 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cli
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: PHP_VERSION=7.2
          tags: |
            gabriel0702usesi/php-multi-arch:7.2
            ghcr.io/oreales/php-cli:7.2
  php71:
    if: ${{ github.event.inputs.php71 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cli
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: PHP_VERSION=7.1
          tags: |
            gabriel0702usesi/php-multi-arch:7.1
            ghcr.io/oreales/php-cli:7.1
  php70:
    if: ${{ github.event.inputs.php70 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cli
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: PHP_VERSION=7.0
          tags: |
            gabriel0702usesi/php-multi-arch:7.0
            ghcr.io/oreales/php-cli:7.0
